version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 10
  pre_build:
    commands:
      - echo Installing dependencies...
      - $(aws ecr get-login --no-include-email --region ap-northeast-2)
  build:
    commands:
      - docker build -t code-pipeline-nestjs .
  post_build:
    commands:
      - docker tag code-pipeline-nestjs:latest 471011865482.dkr.ecr.ap-northeast-2.amazonaws.com/code-pipeline-nestjs:latest
      - docker push 471011865482.dkr.ecr.ap-northeast-2.amazonaws.com/code-pipeline-nestjs:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' code-pipeline-nestjs-app 471011865482.dkr.ecr.ap-northeast-2.amazonaws.com/code-pipeline-nestjs > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
